name = "VegaGraphs"
uuid = "77fd37bf-cb98-4fe5-80a7-6b0508cae6f0"
authors = ["jpbrasile <jean-pierre.brasile@effitech.eu> and contributors"]
version = "0.1.0"

[deps]
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
